# This is an action that will automatically create a build when there is a push to main.
name: "pre-release"

on:
  push:
    branches:
      - "main"
      
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # Clone the repo
      - uses: actions/checkout@v3
  
      # Install Ninja
      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Create build directory
        run: |
          echo "CURRENT DIR CONTENTS:"
          pwd
          ls -al
          mkdir build
          cd build
          pwd
        working-directory: ./
        
      - name: Configure Ninja build files
        run: |
          cmake -G "Ninja" -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="" -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="GameBoy" -DCMAKE_BUILD_TYPE="Release" ../llvm
        working-directory: ./build

      - name: "Build with ninja"
        run: |
          ninja
        working-directory: ./build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./build/*
